In [1]:

import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age',]],df.bought_insurance,test_size=0.2, random_state=25)

In [4]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [5]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(1,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=1000)

C:\Users\HP\anaconda3\envs\lokesh\lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5238 - loss: 0.6541
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5238 - loss: 0.6540
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5238 - loss: 0.6539
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5238 - loss: 0.6538
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5238 - loss: 0.6537
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5238 - loss: 0.6536
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5238 - loss: 0.6535
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5238 - loss: 0.6535
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5238 - loss: 0.6534
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5238 - loss: 0.6533
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5238 - loss: 0.6532
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0

In [ ]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step - accuracy: 1.0000 - loss: 0.5571


[0.5570709109306335, 1.0]

In [7]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[0.5782466 ],
       [0.4249525 ],
       [0.46705344],
       [0.47767663],
       [0.58860564],
       [0.6488415 ]], dtype=float32)

In [8]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [9]:
coef, intercept = model.get_weights()

In [10]:
coef, intercept

(array([[2.131224]], dtype=float32), array([-0.68609565], dtype=float32))

In [11]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))

In [12]:
X_test

age
2    47
10   18
21   26
11   28
14   49
9    61

In [14]:
def prediction_function(age):
    weighted_sum = coef[0]*age + intercept
    return sigmoid(weighted_sum)

prediction_function(.47)

C:\Users\HP\AppData\Local\Temp\ipykernel_12912\2829615594.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.5782465890105389

In [15]:
prediction_function(.18)

C:\Users\HP\AppData\Local\Temp\ipykernel_12912\2829615594.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.4249524792030459

In [16]:
#implementing the gradientn descent
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

In [17]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [18]:
def gradient_descent(age, y_true, epochs, loss_thresold):
    w1 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, bias

In [20]:
gradient_descent(X_train_scaled['age'],y_train,1000, 0.4631)

Epoch:0, w1:1.0083465032642258, bias:-0.037272383770359595, loss:0.6540946856526263
Epoch:1, w1:1.018282763697674, bias:-0.07047432847271615, loss:0.6513152025142919
Epoch:2, w1:1.0295894297049526, bias:-0.10015008081960154, loss:0.6490163845984518
Epoch:3, w1:1.0420737315946784, bias:-0.12677724684147568, loss:0.6470765100804029
Epoch:4, w1:1.0555671842134278, bias:-0.1507727772568578, loss:0.6454042303777039
Epoch:5, w1:1.0699231516565204, bias:-0.17249921028487547, loss:0.643931307643345
Epoch:6, w1:1.0850144363277552, bias:-0.19227079042906106, loss:0.64260695151474
Epoch:7, w1:1.1007309892228956, bias:-0.2103592398040811, loss:0.6413934643089864
Epoch:8, w1:1.1169777939146324, bias:-0.2269990648913611, loss:0.6402629272727233
Epoch:9, w1:1.1336729475930718, bias:-0.24239235065283837, loss:0.6391946989572899
Epoch:10, w1:1.150745944100281, bias:-0.25671303705927107, loss:0.6381735381204536
Epoch:11, w1:1.1681361527793686, bias:-0.270110698694548, loss:0.6371882018230636
Epoch:12, w

(7.085907656567274, -2.701227223797351)

In [21]:
coef, intercept

(array([[2.131224]], dtype=float32), array([-0.68609565], dtype=float32))