In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age',]],df.bought_insurance,test_size=0.2, random_state=25)

In [5]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(1,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5238 - loss: 0.6541
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5238 - loss: 0.6540
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5238 - loss: 0.6539
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5238 - loss: 0.6538
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5238 - loss: 0.6537
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5238 - loss: 0.6536
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5238 - loss: 0.6535
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5238 - loss: 0.6535
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5238 - loss: 0.6534
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5238 - loss: 0.6533
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5238 - loss: 0.6532
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0

In [12]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.5571


[0.5570709109306335, 1.0]

In [13]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[0.5782466 ],
       [0.4249525 ],
       [0.46705344],
       [0.47767663],
       [0.58860564],
       [0.6488415 ]], dtype=float32)

In [14]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [15]:
coef, intercept = model.get_weights()

In [16]:
coef, intercept

(array([[2.131224]], dtype=float32), array([-0.68609565], dtype=float32))

In [17]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))

In [18]:
X_test

age
2    47
10   18
21   26
11   28
14   49
9    61

In [19]:
def prediction_function(age):
    weighted_sum = coef[0]*age  + intercept
    return sigmoid(weighted_sum)

prediction_function(.47)

C:\Users\HP\AppData\Local\Temp\ipykernel_21484\2829615594.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.5782465890105389

In [20]:
prediction_function(.18)

C:\Users\HP\AppData\Local\Temp\ipykernel_21484\2829615594.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.4249524792030459

In [21]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))


In [22]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [23]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1,  self.bias = self.gradient_descent(X['age'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1},  bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] +  self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age, y_true, epochs, loss_thresold):
        w1  = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
           

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
           
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, bias:{bias}, loss:{loss}')
                break

        return w1, bias

In [24]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)

Epoch:0, w1:1.0083465032642258, bias:-0.037272383770359595, loss:0.6540946856526263
Epoch:50, w1:1.8817028970231726, bias:-0.5982089406430177, loss:0.6052327564496791
Epoch:100, w1:2.7155975240633086, bias:-0.9367012866431007, loss:0.572672078276125
Epoch:150, w1:3.4539254359274945, bias:-1.2356321856507464, loss:0.5471702532864451
Epoch:200, w1:4.110186332706321, bias:-1.5009092931224077, loss:0.5270358269776041
Epoch:250, w1:4.695931596586122, bias:-1.7374207915325912, loss:0.5110041496008094
Epoch:300, w1:5.220907607674852, bias:-1.949239762835869, loss:0.4981315968726304
Epoch:350, w1:5.693298407606746, bias:-2.1397546408726353, loss:0.48771196756850665
Epoch:400, w1:6.119972165192524, bias:-2.3117889128609725, loss:0.4792135845807942
Epoch:450, w1:6.506704382499587, bias:-2.467703840826141, loss:0.47223310510098715
Epoch:500, w1:6.858369132797913, bias:-2.6094835752389005, loss:0.46646195458012635
Epoch:535, w1:7.085907656567274, bias:-2.701227223797351, loss:0.46301190740694576
F

In [25]:
coef, intercept

(array([[2.131224]], dtype=float32), array([-0.68609565], dtype=float32))

In [26]:
X_test_scaled

age
2   0.47
10  0.18
21  0.26
11  0.28
14  0.49
9   0.61

In [27]:
customModel.predict(X_test_scaled)

2     0.652297
10    0.193760
21    0.297571
11    0.328016
14    0.683709
9     0.834957
Name: age, dtype: float64

In [28]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[0.5782466 ],
       [0.4249525 ],
       [0.46705344],
       [0.47767663],
       [0.58860564],
       [0.6488415 ]], dtype=float32)